[package]
name = "macnickenson"
version = "0.1.0"
authors = ["Stefan Schwarz <stefan@f2o.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.3"
async-std = { version = "1.6", features = ["attributes"] }
sqlx = "0.3"
tide = "0.13"
