[package]
name = "macnickenson"
version = "0.1.0"
authors = ["Stefan Schwarz <stefan@f2o.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.3"
askama = "0.8"
async-std = { version = "1.6", features = ["attributes"] }
chrono = "0.4"
sqlx = { version = "0.4.0-beta.1", features = ["mysql", "chrono", "macros"] }
tide = "0.13"
